//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RichardSzalay.Web.Deployment.WindowsService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RichardSzalay.Web.Deployment.WindowsService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding virtual path ({0}).
        /// </summary>
        internal static string AddingContentPathMessage {
            get {
                return ResourceManager.GetString("AddingContentPathMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectoryAlreadyExists.
        /// </summary>
        internal static string DirectoryAlreadyExists {
            get {
                return ResourceManager.GetString("DirectoryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileAlreadyExists.
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string FileNotFound_FileName {
            get {
                return ResourceManager.GetString("FileNotFound_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Path Provider.
        /// </summary>
        internal static string ProviderFriendlyNameServicePath {
            get {
                return ResourceManager.GetString("ProviderFriendlyNameServicePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ServicePathLibProviderAddMessage {
            get {
                return ResourceManager.GetString("ServicePathLibProviderAddMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ServicePathLibProviderDeleteMessage {
            get {
                return ResourceManager.GetString("ServicePathLibProviderDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ServicePathLibProviderUpdateMessage {
            get {
                return ResourceManager.GetString("ServicePathLibProviderUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Service Content.
        /// </summary>
        internal static string ServicePathProviderDescription {
            get {
                return ResourceManager.GetString("ServicePathProviderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of seconds that will be allowed when starting or stopping the service.
        /// </summary>
        internal static string ServiceTimeoutSettingDescription {
            get {
                return ResourceManager.GetString("ServiceTimeoutSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Timeout.
        /// </summary>
        internal static string ServiceTimeoutSettingFriendlyName {
            get {
                return ResourceManager.GetString("ServiceTimeoutSettingFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping &apos;{0}&apos; action on service state file &apos;{1}&apos;.
        /// </summary>
        internal static string SkipServiceStateEvent {
            get {
                return ResourceManager.GetString("SkipServiceStateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skips Service state files (.InstallLog, .InstallState).
        /// </summary>
        internal static string SkipServiceStateRuleDescription {
            get {
                return ResourceManager.GetString("SkipServiceStateRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Service State.
        /// </summary>
        internal static string SkipServiceStateRuleFriendlyName {
            get {
                return ResourceManager.GetString("SkipServiceStateRuleFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting service: {0}.
        /// </summary>
        internal static string StartingServiceEvent {
            get {
                return ResourceManager.GetString("StartingServiceEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts the Windows Service after the deployment completes.
        /// </summary>
        internal static string StartServiceRuleDescription {
            get {
                return ResourceManager.GetString("StartServiceRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Service.
        /// </summary>
        internal static string StartServiceRuleFriendlyName {
            get {
                return ResourceManager.GetString("StartServiceRuleFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping service: {0}.
        /// </summary>
        internal static string StoppingServiceEvent {
            get {
                return ResourceManager.GetString("StoppingServiceEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops the Windows Service after deployment completes.
        /// </summary>
        internal static string StopServiceRuleDescription {
            get {
                return ResourceManager.GetString("StopServiceRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Service.
        /// </summary>
        internal static string StopServiceRuleFriendlyName {
            get {
                return ResourceManager.GetString("StopServiceRuleFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown service name: {0}.
        /// </summary>
        internal static string UnknownServiceName {
            get {
                return ResourceManager.GetString("UnknownServiceName", resourceCulture);
            }
        }
    }
}
